version = 1

[update]
always = true                      # default: false
require_automerge_label = true     # default: true
ignored_usernames = ["dependabot"]

[merge]
method = "squash"
automerge_label = "automerge"
blocking_labels = ["blocking"]

[merge.message]
title = "pull_request_title"
body = "empty"
include_pr_number = true

[merge.automerge_dependencies]
versions = ["minor", "patch"]
usernames = ["dependabot"]

[approve]
auto_approve_usernames = ["dependabot", "marcocondrache"]
